### PR TITLE
feat: result page

### PR DESCRIPTION
**Pull request by vrx29**
Live Preview : https://gimesto-quiz-git-result-vrx29.vercel.app/

Result page for Quiz app- It will display all the answers selected by the user are correct or not if not correct the correct answer will also be highlighted
Also user will be able to see Result and score of their quiz.

### CODE REVIEW

**Review by anik31 — APPROVED** [review]
Great work @vrx29, Everything looks good. The quiz flow is working perfectly in the preview & the UI is also very nice.

**Comment by VLeads** [comment]
Ui is good . 4th question doesn't highlight which is right answer. It only shows wrong answer.

**Review by VLeads — APPROVED** [review]
There is nothing in code to suggest. All good !

**Review by Vishnu-Aithal — COMMENTED** [review]
Code looks Good and Readable, 

Bugs : 4th Question in results page doesn't show the correct answer for God of War and Mario Quiz, maybe bug in database.

suggestions : prevent user from going back from "results page" to "Q5 page" if user clicks back button in browser.

**Review by Vishnu-Aithal — APPROVED** [review]

**Comment by vrx29** [comment]
@VLeads @Vishnu-Aithal fixed 4 ques issue. thanks for suggesting

**Pull request merged**
